name: uniresys
description: A new Flutter application.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  page_transition: "^1.1.7+2"

  provider: ^4.3.2+2

  firebase_core: "0.5.0+1"
  firebase_auth: "^0.18.1+1"
  cloud_firestore: ^0.14.1+3

  email_validator: ^1.0.0

  cupertino_icons: ^0.1.3

  flutter_spinkit: "^4.1.2"

  loading_overlay: ^0.2.1

  flutter_launcher_icons: ^0.8.1

  flutter_inner_drawer: ^0.5.7+2

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/feedback.png